plugins {
    id 'net.fabricmc.fabric-loom'
}

dependencies {
    minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    api "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
    implementation "dev.isxander:yet-another-config-lib:${rootProject.yacl_version}-fabric"
    compileOnly "com.terraformersmc:modmenu:${rootProject.modmenu_version}"
    runtimeOnly "com.terraformersmc:modmenu:${rootProject.modmenu_version}"
    compileOnly "maven.modrinth:DistantHorizonsApi:${rootProject.distant_horizons_api_version}"
}

tasks.named('processResources', ProcessResources).configure {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    var replaceProperties = [
            minecraft_version_range : rootProject.minecraft_version_range,
            fabric_loader_version : rootProject.fabric_loader_version,
            fabric_api_version    : rootProject.fabric_api_version,
            modmenu_version       : rootProject.modmenu_version,
            yacl_version          : rootProject.yacl_version,
            mod_id                : rootProject.mod_id,
            mod_name              : rootProject.mod_name,
            mod_license           : rootProject.mod_license,
            mod_version           : rootProject.mod_version,
            mod_authors           : rootProject.mod_authors,
            mod_description       : rootProject.mod_description,
            mod_display_url       : rootProject.mod_display_url,
            mod_issue_tracker     : rootProject.mod_issue_tracker,
            mod_package           : rootProject.maven_group,
    ]
    inputs.properties replaceProperties

    filesMatching('fabric.mod.json') {
        expand replaceProperties
    }
}

tasks.named('sourcesJar', Jar).configure {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
