plugins {
    id 'dev.architectury.loom' version '1.14.473' apply false
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

allprojects {
    version = rootProject.mod_version
    group = rootProject.maven_group

    repositories {
        mavenCentral()
        maven {
            name = 'Xander Maven'
            url = 'https://maven.isxander.dev/releases'
        }
        maven {
            name = 'NeoForge'
            url = 'https://maven.neoforged.net/releases/'
        }
        maven {
            name = 'ParchmentMC'
            url = 'https://maven.parchmentmc.org/'
        }
    }
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'dev.architectury.loom'

    base {
        archivesName = "${rootProject.archives_base_name}-${project.name}-${rootProject.minecraft_version}"
    }

    java {
        toolchain.languageVersion = JavaLanguageVersion.of(rootProject.java_version.toInteger())
        withSourcesJar()
    }

    loom {
        silentMojangMappingsLicense()
    }

    dependencies {
        minecraft "com.mojang:minecraft:${rootProject.minecraft_version}"
        mappings loom.layered {
            officialMojangMappings()
            parchment("org.parchmentmc.data:parchment-${rootProject.parchment_minecraft_version}:${rootProject.parchment_mappings_version}@zip")
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = rootProject.java_version.toInteger()
    }

}
