org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Build Properties
java_version=21

# Minecraft Properties
minecraft_version=1.21.1
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Dependency Versions
neo_version=21.1.247
yacl_version=3.8.1+1.21.1-neoforge
architectury_version=13.0.8
toucanlib_version=0.4.0
toucanlib_neoforge_version=0.4.0-neoforge
useLocalToucanLib=false
distant_horizons_api_version=7.0.0

# Loader Ranges
minecraft_version_range=[1.21.1]
loader_version_range=[1,)

## Mod Properties
mod_id=cirrus
mod_name=Cirrus
mod_authors=jvn
mod_license=All Rights Reserved
mod_version=1.2.0
maven_group=com.jvn.cirrus
archives_base_name=cirrus
mod_description=The sky's the beginning.
mod_display_url=https://github.com/JevenDev/Cirrus
mod_issue_tracker=https://github.com/JevenDev/Cirrus/issues
